spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8080