spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimeZone=UTC&CharacterEncoding=UTF-8
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
  r2dbc:
    url: r2dbc:pool:mysql:://localhost:3306/test?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/test?serverTimeZone=UTC&CharacterEncoding=UTF-8
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

server:
  port: 8080